---
- hosts: all
  become: yes
  become_user: root
  gather_facts: true

  vars:
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    epel_repofile_path: "/etc/yum.repos.d/epel.repo"
    epel_repo_gpg_key_path: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    COLLECT_INTERVAL: 5
    GRAPHITE_HOST: localhost

  tasks:
    - name: Check if EPEL repo is already configured.
      stat: path={{ epel_repofile_path }}
      register: epel_repofile_result

    - name: Install EPEL repo.
      yum:
        name: "{{ epel_repo_url }}"
        state: present
      when: not epel_repofile_result.stat.exists

    - name: Check if EPEL Repo GPG Key is already imported.
      stat: path={{ epel_repo_gpg_key_path }}
      register: epel_repo_gpg_key_result

    - name: Import EPEL GPG key.
      rpm_key:
        key: "{{ epel_repo_gpg_key_url }}"
        state: present
      when: not epel_repo_gpg_key_result.stat.exists

    - name: Check if collectd is already installed.
      package_facts:
        manager: auto

    - name: Install collectd package from EPEL repo
      yum:
        name: collectd
        state: present
      when: "'collectd' not in ansible_facts.packages"

    - name: Start collectd service
      service:
        name: collectd
        enabled: yes
        state: started
        
    - name: Configure collectd to send the data to the performance monitoring aggregator/relay
      template:
        src: collectd.conf
        dest: /etc/collectd.conf
      notify: restart collectd service

  handlers:
    - name: restart collectd service
      service:
        name: collectd
        state: restarted